set $mod Mod4

set $monitor-left   eDP-1
set $monitor-right HDMI-A-2

set $wallpaper1 ~/.config/wallpapers/the_book_and_old_converses.png
set $wallpaper2 ~/.config/wallpapers/quiet_babushkas_rug.png

set $browser firefox

set $kbd_layout  us,ru
set $kbd_variant "colemak,"
set $kbd_options grp:alt_shift_toggle